spring:
  profiles: development
security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: "http://localhost:8001/uaa/oauth/token_key"
yikejian:
  user:
    api:
      url: "http://user-service/uaa/v1/me"
  customer:
    api:
      url:
            