spring:
  profiles: development
security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: "http://localhost:8001/uaa/oauth/token_key"
yikejian:
  user:
    api:
      url: "http://user-service/uaa/v1/me"
  message:
    # 超时时间
    connectTimeout: "10000"
    readTimeout: "10000"
    # 短信API产品名称（短信产品名固定，无需修改）
    product: "Dysmsapi"
    # 短信API产品域名（接口地址固定，无需修改）
    domain: "dysmsapi.aliyuncs.com"
    # aliyun accessKey
    accessKeyId: ""
    # aliyun accessKeySecret
    accessKeySecret: ""
    # region 暂时不支持多region（请勿修改）
    region: "cn-hangzhou"
    # 短信签名-可在短信控制台中找到
    sign: ""
    # 短信模板-可在短信控制台中找到
    templateCode: ""
