spring:
  profiles:
    active: development

##############
# log config #
##############
logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
#    org.springframework.security: DEBUG
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://localhost:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      me: "http://localhost:8001/user-service/v1/me"
      user: "http://localhost:8001/user-service/v1/user"
      token: "http://localhost:8001/user-service/oauth/token"
  message:
    url: "http://localhost:8011/message-service/v1/message"
    code:
      template: "【一刻间】您好，您的验证码是：%s，有效时间5分钟"
weixin:
  token:
    url: "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.99.1:3306/customer?characterEncoding=utf-8
    username: root
    password: 123456
    initialize: true
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://192.168.1.101:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      me: "http://192.168.1.101:8001/user-service/v1/me"
      user: "http://192.168.1.101:8001/user-service/v1/user"
      token: "http://192.168.1.101:8001/user-service/oauth/token"
  message:
    url: "http://192.168.1.101:8011/message-service/v1/message"
    code:
      template: "【一刻间】您好，您的验证码是：%s，有效时间5分钟"
weixin:
  token:
    url: "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://rm-wz9zran8v261152v0.mysql.rds.aliyuncs.com:3306/customer?characterEncoding=utf-8
    username: root
    password: neomal2018@)!*
    initialize: true
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://localhost:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      me: "http://localhost:8001/user-service/v1/me"
      user: "http://localhost:8001/user-service/v1/user"
      token: "http://localhost:8001/user-service/oauth/token"
  message:
    url: "http://localhost:8011/message-service/v1/message"
    code:
      template: "【一刻间】您好，您的验证码是：%s，有效时间5分钟"
weixin:
  token:
    url: "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
