spring:
  profiles: development
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://localhost:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      url: "http://localhost:8001/user-service/v1/me"
  customer:
    api:
      url: "http://localhost:8002/customer-service/v1/me"
weixin:
  pay:
    prepay:
      url: "https://api.mch.weixin.qq.com/pay/unifiedorder"
    mch_id: 1324562801
    key: Yikejian001842015704713502801188
    notify_url:
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.99.1:3306/payment?characterEncoding=utf-8
    username: root
    password: 123456
    initialize: true
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://192.168.1.101:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      url: "http://192.168.1.101:8001/user-service/v1/me"
  customer:
    api:
      url: "http://192.168.1.101:8002/customer-service/v1/me"
weixin:
  pay:
    prepay:
      url: "https://api.mch.weixin.qq.com/pay/unifiedorder"
    mch_id: 1324562801
    key: Yikejian001842015704713502801188
    notify_url:
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://rm-wz9zran8v261152v0.mysql.rds.aliyuncs.com:3306/payment?characterEncoding=utf-8
    username: root
    password: neomal2018@)!*
    initialize: true
security:
  oauth2:
    resource:
      jwt:
        key-uri: "http://localhost:8001/user-service/oauth/token_key"
yikejian:
  user:
    api:
      url: "http://localhost:8001/user-service/v1/me"
  customer:
    api:
      url: "http://localhost:8002/customer-service/v1/me"
weixin:
  pay:
    prepay:
      url: "https://api.mch.weixin.qq.com/pay/unifiedorder"
    mch_id: 1324562801
    key: Yikejian001842015704713502801188
    notify_url:
  app:
    id: wx74e6f71fdef09122
    secret: 54ee7d4db46487a5cd01492ad9911ed2
