spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
        native:
          search-locations: file:E:\yikejian-parent\config
