spring:
  profiles: development
security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: "http://localhost:8001/user-service/oauth/token_key"
yikejian:
  api:
    user:
      url: "http://user-service/user-service/v1/me"
    product:
      url: "http://product-service/product-service/"
    inventory:
      url: "http://inventory-service/inventory-service/"